### ISSUE TITLE
Issue converting multiple PGN to FEN

### ISSUE THREAD

**Issue by Chaaronn** [SindreSvendby/pgnToFen#9]
I know this is an old lib, I've just started using it to create a chess engine that plays unseen moves from the opponent. 

I've got an issue with pgnFile() giving me the same FEN for every game. [Here's my code.](https://imgur.com/a/nQFK8nw)

The output I'm getting is [this.](https://imgur.com/a/B3VfTX0) The FEN list contains the same game each time. 

If you feel like picking up an old project and helping me out I'd appreciate it. :)

**Comment by abhinav7sinha** [comment]
@Chaaronn I can take a look. Do you mind sharing a link to your PGN files?

**Comment by Chaaronn** [comment]
[here you go](https://raw.githubusercontent.com/Chaaronn/unseen_chess/main/last200.pgn?token=GHSAT0AAAAAABZAD7PXD4RELQMRRSZDEO5MYZKIUUA), this is modified from my set with the top 3 from the troll masters set on the repo as I thought it could be a formatting issue.

**Comment by abhinav7sinha** [comment]
I get a 404 when I click on it - is it a private repo?

**Comment by Chaaronn** [comment]
I viewed it in a private tab, but I'll change it to public now

**Comment by abhinav7sinha** [comment]
Thanks - I'll take a look - later tonight and get back.

**Comment by abhinav7sinha** [comment]
Hey @Chaaronn - The issue was with the global class variables not being defined inside of constructors. I've fixed it - and opened a PR. Until it's merged - you can use my fork from here - https://github.com/abhinav7sinha/pgnToFen/tree/issue-9-multiple-pgn
And sorry about the delay.

**Comment by SindreSvendby** [comment]
Merged in to master now @Chaaronn.

Thanks for your contribution @abhinav7sinha

**Comment by Chaaronn** [comment]
Thank you mate! It's for a uni project so I appreciate it

**Comment by abhinav7sinha** [comment]
> Thank you mate! It's for a uni project so I appreciate it

You're welcome @Chaaronn 
Happy to help :) I'm in uni too - working on chess stuff :)
